import type { Preset } from '../types'

const VERIFIED_AT = '2026-10-05'

export const US_PRESET: Preset = {
  id: 'us-passport',
  label: 'USA – Reisepass (2 × 2 Zoll)',
  labelEn: 'USA – passport (2 × 2 in)',
  group: 'americas',
  region: 'US',
  widthMm: 50.8,
  heightMm: 50.8,
  dpi: 600,
  head: { minMm: 25, maxMm: 35, targetMm: 31 },
  topMarginMm: 6,
  freeSpaceTopRatio: 0.3,
  eyeLineFromTop: 0.38,
  eyeLineRangeFromTop: [0.31, 0.451],
  background: {
    tones: ['weiss', 'hellgrau'],
    allowPureWhite: true,
    minLuminance: 0.78,
    minContrast: 0.16,
    uniformRequired: true,
  },
  glasses: 'verboten',
  headCovering: 'religioes',
  digital: {
    widthPx: 600,
    heightPx: 600,
    maxWidthPx: 1200,
    maxHeightPx: 1200,
    minBytes: 54_000,
    maxBytes: 10_485_760,
    formats: ['jpeg', 'png'],
    quality: 0.92,
    aspectTolerancePercent: 0,
  },
  printSheets: ['letter', '4x6'],
  printCopies: 1,
  maxAgeMonths: 6,
  notes: [
    'Brille ist seit 2016 nicht mehr erlaubt – auch nicht mit dünnem Rahmen.',
    'Digitale Bearbeitung ist untersagt, ausdrücklich auch KI-gestützte Hintergrundentfernung oder -ersetzung.',
    'Kopfhöhe 25–35 mm vom Kinn bis zum Scheitel, Augen 56–69 % der Bildhöhe von unten.',
    'Digital-Upload: 600 × 600 px bis 1200 × 1200 px, 54 kB bis 10 MB.',
  ],
  source: {
    label: 'travel.state.gov – Passport Photos',
    url: 'https://travel.state.gov/en/passports/apply/help/photos.html',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const US_VISA_PRESET: Preset = {
  id: 'us-visa',
  label: 'USA – Visum (2 × 2 Zoll, ≤ 240 kB)',
  labelEn: 'USA – visa (2 × 2 in, ≤ 240 kB)',
  group: 'americas',
  region: 'US',
  widthMm: 50.8,
  heightMm: 50.8,
  dpi: 600,
  head: { minMm: 25, maxMm: 35, targetMm: 31 },
  topMarginMm: 6,
  eyeLineFromTop: 0.38,
  eyeLineRangeFromTop: [0.31, 0.451],
  background: {
    tones: ['weiss', 'hellgrau'],
    allowPureWhite: true,
    minLuminance: 0.78,
    minContrast: 0.16,
    uniformRequired: true,
  },
  glasses: 'verboten',
  headCovering: 'religioes',
  digital: {
    widthPx: 600,
    heightPx: 600,
    maxWidthPx: 1200,
    maxHeightPx: 1200,
    maxBytes: 240_000,
    formats: ['jpeg'],
    quality: 0.85,
    aspectTolerancePercent: 0,
  },
  printSheets: ['letter', '4x6'],
  printCopies: 1,
  maxAgeMonths: 6,
  notes: [
    'Quadratisch, JPEG, 600 × 600 bis 1200 × 1200 px, maximal 240 kB.',
    'Kopfhöhe digital 50–69 % der Bildhöhe vom Kinn bis zum Scheitel.',
    'Zusätzlich kann die Vorlage ein ausgedrucktes 2 × 2-Zoll-Foto verlangen.',
  ],
  source: {
    label: 'travel.state.gov – Digital Image Requirements',
    url: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos/digital-image-requirements.html',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const CANADA_PRESET: Preset = {
  id: 'ca-passport',
  label: 'Kanada – Reisepass (50 × 70 mm)',
  labelEn: 'Canada – passport (50 × 70 mm)',
  group: 'americas',
  region: 'CA',
  widthMm: 50,
  heightMm: 70,
  dpi: 600,
  head: { minMm: 31, maxMm: 36, targetMm: 33.5, minRatio: 0.45, maxRatio: 0.5 },
  freeSpaceTopRatio: 0.28,
  background: {
    tones: ['weiss', 'hellgrau'],
    allowPureWhite: true,
    minLuminance: 0.7,
    minContrast: 0.15,
    uniformRequired: true,
  },
  glasses: 'ohne-tinte',
  headCovering: 'religioes',
  digital: {
    minWidthPx: 1200,
    minHeightPx: 1800,
    maxWidthPx: 3000,
    maxHeightPx: 4500,
    minBytes: 200_000,
    maxBytes: 5_242_880,
    formats: ['jpeg'],
    quality: 0.92,
    aspectTolerancePercent: 2,
  },
  printSheets: ['4x6', 'letter'],
  printCopies: 1,
  maxAgeMonths: 6,
  notes: [
    'Gesichtshöhe 31–36 mm bzw. 45–50 % der Bildhöhe.',
    'Digital: JPEG im Seitenverhältnis 3:2, 1200 × 1800 bis 3000 × 4500 px, 200 kB bis 5 MB.',
  ],
  source: {
    label: 'canada.ca – Passport photo requirements',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-passports/photos.html',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const BRAZIL_PRESET: Preset = {
  id: 'br-passport',
  label: 'Brasilien – Reisepass (5 × 7 cm)',
  labelEn: 'Brazil – passport (5 × 7 cm)',
  group: 'americas',
  region: 'BR',
  widthMm: 50,
  heightMm: 70,
  dpi: 600,
  // Kopf nimmt rund 45 % der Bildhöhe ein, nicht 70 % (5 × 7 cm Blattformat).
  head: { minMm: 29, maxMm: 33, targetMm: 31, minRatio: 0.42, maxRatio: 0.47 },
  freeSpaceTopRatio: 0.22,
  background: {
    tones: ['weiss', 'hellgrau'],
    allowPureWhite: true,
    minLuminance: 0.7,
    minContrast: 0.14,
    uniformRequired: true,
  },
  glasses: 'ohne-tinte',
  headCovering: 'religioes',
  digital: {
    formats: ['jpeg'],
    quality: 0.92,
    minWidthPx: 600,
    minHeightPx: 840,
  },
  printSheets: ['4x6', 'a4'],
  printCopies: 2,
  maxAgeMonths: 6,
  notes: [
    'Kopf nimmt rund 45 % der Bildhöhe ein (ca. 30–33 mm).',
    'Hintergrund hell, vorzugsweise weiß.',
    'Antragsspezifikation der ausstellenden Behörde vor dem Einreichen prüfen.',
  ],
  source: { label: 'ANAC / ICAO-Leitfaden (gov.br)', url: 'https://www.gov.br/anac/pt-br' },
  verifiedAt: VERIFIED_AT,
  confidence: 'praxis',
}