import type { Preset } from '../types'

const VERIFIED_AT = '2026-10-06'

const BG_WHITE: Preset['background'] = {
  tones: ['weiss', 'hellgrau'],
  allowPureWhite: true,
  minLuminance: 0.65,
  minContrast: 0.12,
  uniformRequired: true,
}

const BG_LIGHT: Preset['background'] = {
  tones: ['hellgrau', 'weiss'],
  allowPureWhite: true,
  minLuminance: 0.6,
  minContrast: 0.12,
  uniformRequired: true,
}

const BG_GREY: Preset['background'] = {
  tones: ['hellgrau'],
  allowPureWhite: false,
  minLuminance: 0.45,
  minContrast: 0.12,
  uniformRequired: true,
}

const PRAXIS_NOTE =
  'Praxiswert: Maße stammen aus Fotodienst-Angaben bzw. Konsulatsformularen und sind nicht vollständig amtlich bestätigt. Vor der Einreichung bitte bei Behörde oder Botschaft prüfen.'

const EU_RASTER_SOURCE = {
  label: 'EU-Verordnung 2252/2004 + ICAO Doc 9303 (Grundraster)',
  url: 'https://eur-lex.europa.eu/eli/reg/2004/2252/oj',
}

interface SpecInput {
  id: string
  region: string
  label: string
  labelEn: string
  group: Preset['group']
  widthMm: number
  heightMm: number
  headTargetMm: number
  headMinMm?: number
  headMaxMm?: number
  topMarginMm?: number
  background?: Preset['background']
  source: { label: string; url: string }
  confidence: Preset['confidence']
  notes?: string[]
  overrides?: Partial<Preset>
}

function spec(input: SpecInput): Preset {
  const freeSpace = input.heightMm - input.headTargetMm
  const top = input.topMarginMm ?? Math.max(1, freeSpace * 0.3)
  const notes = [...(input.notes ?? [])]
  if (input.confidence === 'praxis') notes.push(PRAXIS_NOTE)
  return {
    id: input.id,
    label: input.label,
    labelEn: input.labelEn,
    group: input.group,
    region: input.region,
    widthMm: input.widthMm,
    heightMm: input.heightMm,
    dpi: 600,
    head: {
      minMm: input.headMinMm ?? Math.round((input.headTargetMm - 2) * 10) / 10,
      maxMm: input.headMaxMm ?? Math.round((input.headTargetMm + 2) * 10) / 10,
      targetMm: input.headTargetMm,
    },
    topMarginMm: top,
    freeSpaceTopRatio: freeSpace > 0 ? Math.min(0.6, top / freeSpace) : 0.3,
    background: input.background ?? BG_WHITE,
    glasses: 'ohne-reflexion',
    headCovering: 'religioes',
    digital: {
      formats: ['jpeg'],
      quality: 0.92,
      minWidthPx: Math.round((input.widthMm / 25.4) * 300),
      minHeightPx: Math.round((input.heightMm / 25.4) * 300),
    },
    printSheets: ['a4', '4x6'],
    printCopies: 2,
    maxAgeMonths: 6,
    notes,
    source: input.source,
    verifiedAt: VERIFIED_AT,
    confidence: input.confidence,
    ...input.overrides,
  }
}

function euRaster(id: string, region: string, label: string, labelEn: string): Preset {
  return spec({
    id,
    region,
    label,
    labelEn,
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: EU_RASTER_SOURCE,
    confidence: 'praxis',
    notes: [
      'EU-/ICAO-Grundraster: 35 × 45 mm, Gesicht 70–80 % der Bildhöhe (ca. 32–36 mm).',
      'Nationale Besonderheiten (Hintergrundton, Fotoaufnahme direkt bei der Behörde) sind hier nicht einzeln geprüft.',
    ],
  })
}

const visafoto = (path: string, label: string) => ({
  label: `${label} (Angaben laut visafoto.com, nicht amtlich)`,
  url: `https://visafoto.com/${path}`,
})

export const MORE_PRESETS: Preset[] = [
  spec({
    id: 'be-passport',
    region: 'BE',
    label: 'Belgien – Reisepass / eID (35 × 45 mm)',
    labelEn: 'Belgium – passport / eID (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: {
      label: 'IBZ – Fotomatrix ICAO (Belgien)',
      url: 'https://www.ibz.rrn.fgov.be/sites/default/files/documents/fr/documents-d-identite/fotomatrix/2016_Matrice_FR.pdf',
    },
    confidence: 'offiziell',
    notes: [
      'Kinn bis Scheitel 32–36 mm, Hintergrund einfarbig, Foto höchstens 6 Monate alt.',
      'Brille und Kopfbedeckung nur aus medizinischen bzw. religiösen Gründen.',
    ],
  }),
  spec({
    id: 'gr-passport',
    region: 'GR',
    label: 'Griechenland – Reisepass (40 × 60 mm)',
    labelEn: 'Greece – passport (40 × 60 mm)',
    group: 'eu',
    widthMm: 40,
    heightMm: 60,
    headTargetMm: 33,
    headMinMm: 30,
    headMaxMm: 36,
    background: BG_GREY,
    source: {
      label: 'passport.gov.gr – Technical Specifications of Passport Photograph',
      url: 'https://www.passport.gov.gr/en/diadikasia-ekdosis/documents/specificationphoto.html',
    },
    confidence: 'offiziell',
    notes: [
      'Kinn bis Stirnoberkante 50–60 % der Bildhöhe (30–36 mm); Schultern bis Haaroberkante 70–75 %.',
      'Hintergrund hell, bevorzugt grau RGB (190, 190, 190) ± 10.',
    ],
    overrides: { head: { minMm: 30, maxMm: 36, targetMm: 33, measureToHairline: true } },
  }),
  spec({
    id: 'ie-passport',
    region: 'IE',
    label: 'Irland – Reisepass (35 × 45 mm)',
    labelEn: 'Ireland – passport (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    background: { tones: ['hellgrau', 'weiss', 'creme'], allowPureWhite: true, minLuminance: 0.6, minContrast: 0.12, uniformRequired: true },
    source: { label: 'ireland.ie – Photo Guidelines For Passports', url: 'https://www.ireland.ie/en/dfa/passports/photo-guidelines/' },
    confidence: 'praxis',
    notes: [
      'Amtlich: gedruckt mindestens 35 × 45 mm, höchstens 38 × 50 mm; Hintergrund hellgrau, weiß oder creme.',
      'Amtlich: digital mindestens 715 × 951 px, JPEG, höchstens 9 MB, nicht älter als 6 Monate.',
      'Die Kopfhöhe ist nicht amtlich in Millimetern angegeben; hier gilt das ICAO-Raster.',
    ],
    overrides: {
      digital: { formats: ['jpeg'], quality: 0.92, minWidthPx: 715, minHeightPx: 951, maxBytes: 9_437_184 },
    },
  }),
  spec({
    id: 'ch-passport',
    region: 'CH',
    label: 'Schweiz – Pass / Identitätskarte (35 × 45 mm)',
    labelEn: 'Switzerland – passport / ID card (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: {
      label: 'fedpol – Kriterien für die Annahme von Fotos (Fotomustertafel)',
      url: 'https://www.fedpol.admin.ch/dam/fedpol/de/data/pass-id/fotomustertafel.pdf.download.pdf/fotomustertafel.pdf',
    },
    confidence: 'praxis',
    notes: ['Beim Pass wird das Foto in der Regel im Passbüro aufgenommen; mitgebrachte Fotos nur bei der Identitätskarte.'],
  }),
  spec({
    id: 'pt-passport',
    region: 'PT',
    label: 'Portugal – Reisepass / Cartão de Cidadão (35 × 45 mm)',
    labelEn: 'Portugal – passport / citizen card (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: visafoto('pt-passport-photo', 'Portugal – Reisepass'),
    confidence: 'praxis',
    notes: ['In Portugal wird das Foto meist direkt bei der Antragstellung aufgenommen.'],
  }),
  euRaster('ro-pasaport', 'RO', 'Rumänien – Pașaport / carte de identitate (35 × 45 mm)', 'Romania – passport / ID card (35 × 45 mm)'),
  euRaster('bg-pasport', 'BG', 'Bulgarien – Reisepass / Personalausweis (35 × 45 mm)', 'Bulgaria – passport / ID card (35 × 45 mm)'),
  euRaster('hr-putovnica', 'HR', 'Kroatien – Putovnica / osobna iskaznica (35 × 45 mm)', 'Croatia – passport / ID card (35 × 45 mm)'),
  euRaster('hu-utlevel', 'HU', 'Ungarn – Útlevél (35 × 45 mm)', 'Hungary – passport (35 × 45 mm)'),
  euRaster('cz-pas', 'CZ', 'Tschechien – Cestovní pas (35 × 45 mm)', 'Czechia – passport (35 × 45 mm)'),
  euRaster('se-pass', 'SE', 'Schweden – Pass (35 × 45 mm)', 'Sweden – passport (35 × 45 mm)'),
  euRaster('dk-pas', 'DK', 'Dänemark – Pas (35 × 45 mm)', 'Denmark – passport (35 × 45 mm)'),
  euRaster('no-pass', 'NO', 'Norwegen – Pass (35 × 45 mm)', 'Norway – passport (35 × 45 mm)'),
  spec({
    id: 'rs-pasos',
    region: 'RS',
    label: 'Serbien – Reisepass (50 × 50 mm)',
    labelEn: 'Serbia – passport (50 × 50 mm)',
    group: 'eu',
    widthMm: 50,
    heightMm: 50,
    headTargetMm: 34,
    headMinMm: 30,
    headMaxMm: 38,
    background: BG_GREY,
    source: {
      label: 'MUP Srbije – Biometrijski pasoš',
      url: 'https://www.mup.gov.rs/wps/wcm/connect/public_cyrillic/pocetna/gradjani/dokumenti+gradjana/putne+isprave/biometrijski+pasos',
    },
    confidence: 'praxis',
    notes: [
      'Amtlich: Foto 50 × 50 mm, en face, einfarbig grauer Hintergrund. Das mitgebrachte Foto ist laut MUP optional – das Passfoto wird bei der Antragstellung aufgenommen.',
      'Die Kopfhöhe ist nicht amtlich angegeben.',
    ],
  }),
  spec({
    id: 'mk-visa',
    region: 'MK',
    label: 'Nordmazedonien – Visum (35 × 45 mm)',
    labelEn: 'North Macedonia – visa (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: visafoto('mk-visa-photo', 'Nordmazedonien – Visum'),
    confidence: 'praxis',
  }),
  spec({
    id: 'ua-passport',
    region: 'UA',
    label: 'Ukraine – Reisepass / Pass (35 × 45 mm)',
    labelEn: 'Ukraine – passport (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3.5,
    background: BG_LIGHT,
    source: visafoto('ua-passport-photo', 'Ukraine – Pass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'ru-passport',
    region: 'RU',
    label: 'Russland – Auslandspass (35 × 45 mm)',
    labelEn: 'Russia – international passport (35 × 45 mm)',
    group: 'eu',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 35,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 4.5,
    source: visafoto('ru-passport-photo', 'Russland – Pass'),
    confidence: 'praxis',
    notes: ['Kopf ca. 70–80 % der Bildhöhe, weißer Hintergrund; Upload über Gosuslugi bis ca. 300 kB.'],
    overrides: {
      digital: { formats: ['jpeg'], quality: 0.9, minWidthPx: 413, minHeightPx: 531, maxBytes: 307_200 },
    },
  }),
  spec({
    id: 'tr-pasaport',
    region: 'TR',
    label: 'Türkei – Reisepass / Kimlik (50 × 60 mm)',
    labelEn: 'Turkey – passport / ID card (50 × 60 mm)',
    group: 'mena-africa',
    widthMm: 50,
    heightMm: 60,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 38,
    topMarginMm: 10,
    source: { label: 'NVİ – Biyometrik fotoğraf özellikleri', url: 'https://www.nvi.gov.tr/istanbul/biyometrik-fotograf-nasil-olmalidir' },
    confidence: 'praxis',
    notes: [
      'Amtlich (NVİ): 50 × 60 mm, weißer Hintergrund ohne Muster, nicht älter als 6 Monate, Gesicht mit Frisur vollständig sichtbar.',
      'Mit Kopftuch muss das Gesicht vom Kinn bis zur Stirn sichtbar sein.',
      'Die Kopfhöhe ist bei der NVİ nicht in Millimetern angegeben; hier gilt ein Praxiswert.',
    ],
    overrides: { background: { ...BG_WHITE, tones: ['weiss'] } },
  }),
  spec({
    id: 'af-passport',
    region: 'AF',
    label: 'Afghanistan – Reisepass (40 × 45 mm)',
    labelEn: 'Afghanistan – passport (40 × 45 mm)',
    group: 'mena-africa',
    widthMm: 40,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 31.5,
    headMaxMm: 36,
    topMarginMm: 3,
    source: {
      label: 'idphotodiy.com unter Berufung auf die afghanische Botschaft (nicht amtlich)',
      url: 'https://www.idphotodiy.com/photo-requirements.php?country=AF&type=Passport',
    },
    confidence: 'praxis',
    notes: [
      'Kopf 70–80 % der Bildhöhe, weißer Hintergrund. Manche Vertretungen verlangen stattdessen 35 × 45 mm oder 50 × 50 mm.',
    ],
  }),
  spec({
    id: 'af-visa',
    region: 'AF',
    label: 'Afghanistan – Visum (35 × 45 mm)',
    labelEn: 'Afghanistan – visa (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    source: visafoto('af-visa-35x45-photo', 'Afghanistan – Visum'),
    confidence: 'praxis',
  }),
  spec({
    id: 'sy-passport',
    region: 'SY',
    label: 'Syrien – Reisepass (40 × 60 mm)',
    labelEn: 'Syria – passport (40 × 60 mm)',
    group: 'mena-africa',
    widthMm: 40,
    heightMm: 60,
    headTargetMm: 38,
    topMarginMm: 6,
    source: visafoto('sy-passport-photo', 'Syrien – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'iq-passport',
    region: 'IQ',
    label: 'Irak – Reisepass (35 × 45 mm)',
    labelEn: 'Iraq – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    source: visafoto('iq-passport-35x45mm-photo', 'Irak – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'pk-passport',
    region: 'PK',
    label: 'Pakistan – Reisepass (35 × 45 mm)',
    labelEn: 'Pakistan – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    topMarginMm: 3.5,
    source: { label: 'DGIP – Photograph Requirements', url: 'https://onlinemrp.dgip.gov.pk/photo-requirements/' },
    confidence: 'praxis',
    notes: [
      'Amtlich (DGIP): 45 mm hoch × 35 mm breit, schlichter weißer Hintergrund, nicht älter als 6 Monate, keine Bildbearbeitung, Datei höchstens 5 MB.',
      'Die Kopfhöhe ist bei der DGIP nicht in Millimetern angegeben.',
    ],
    overrides: { digital: { formats: ['jpeg'], quality: 0.92, minWidthPx: 413, minHeightPx: 531, maxBytes: 5_242_880 } },
  }),
  spec({
    id: 'jo-passport',
    region: 'JO',
    label: 'Jordanien – Reisepass (35 × 45 mm)',
    labelEn: 'Jordan – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 33,
    topMarginMm: 4,
    source: visafoto('jo-passport-photo', 'Jordanien – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'lb-passport',
    region: 'LB',
    label: 'Libanon – Reisepass (35 × 45 mm)',
    labelEn: 'Lebanon – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    topMarginMm: 3,
    source: visafoto('lb-passport-photo', 'Libanon – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'il-passport',
    region: 'IL',
    label: 'Israel – Reisepass (35 × 45 mm)',
    labelEn: 'Israel – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 32,
    topMarginMm: 5,
    background: BG_LIGHT,
    source: visafoto('il-passport-photo', 'Israel – Reisepass'),
    confidence: 'praxis',
    notes: ['Israel akzeptiert laut Angabe auch 50 × 50 mm.'],
  }),
  spec({
    id: 'eg-passport',
    region: 'EG',
    label: 'Ägypten – Reisepass (40 × 60 mm)',
    labelEn: 'Egypt – passport (40 × 60 mm)',
    group: 'mena-africa',
    widthMm: 40,
    heightMm: 60,
    headTargetMm: 40,
    headMinMm: 38,
    headMaxMm: 44,
    topMarginMm: 6,
    source: {
      label: 'makepassportphoto.com – Egypt passport (nicht amtlich)',
      url: 'https://makepassportphoto.com/en/p/photo-for-egypt-passport',
    },
    confidence: 'praxis',
  }),
  spec({
    id: 'ma-passport',
    region: 'MA',
    label: 'Marokko – Reisepass (35 × 45 mm)',
    labelEn: 'Morocco – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 35,
    topMarginMm: 3,
    source: visafoto('ma-passport-photo', 'Marokko – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'dz-passport',
    region: 'DZ',
    label: 'Algerien – Reisepass (35 × 45 mm)',
    labelEn: 'Algeria – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3.5,
    source: visafoto('dz-passport-photo', 'Algerien – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'tn-passport',
    region: 'TN',
    label: 'Tunesien – Reisepass (35 × 45 mm)',
    labelEn: 'Tunisia – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 33,
    topMarginMm: 4,
    source: visafoto('tn-passport-photo', 'Tunesien – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'ng-passport',
    region: 'NG',
    label: 'Nigeria – Reisepass (35 × 45 mm)',
    labelEn: 'Nigeria – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 4.5,
    source: visafoto('ng-passport-photo', 'Nigeria – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'et-passport',
    region: 'ET',
    label: 'Äthiopien – Reisepass (30 × 40 mm)',
    labelEn: 'Ethiopia – passport (30 × 40 mm)',
    group: 'mena-africa',
    widthMm: 30,
    heightMm: 40,
    headTargetMm: 30,
    topMarginMm: 2.5,
    source: visafoto('et-passport-3x4-photo', 'Äthiopien – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'za-passport',
    region: 'ZA',
    label: 'Südafrika – Reisepass (35 × 45 mm)',
    labelEn: 'South Africa – passport (35 × 45 mm)',
    group: 'mena-africa',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: visafoto('za-passport-photo', 'Südafrika – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'in-visa',
    region: 'IN',
    label: 'Indien – Visum (2 × 2 Zoll, quadratisch)',
    labelEn: 'India – visa (2 × 2 in, square)',
    group: 'asia-pacific',
    widthMm: 50.8,
    heightMm: 50.8,
    headTargetMm: 31,
    headMinMm: 25,
    headMaxMm: 35,
    topMarginMm: 6,
    source: { label: 'indianvisaonline.gov.in – Instructions for Regular Visa Application', url: 'https://indianvisaonline.gov.in/visa/instruction.html' },
    confidence: 'offiziell',
    notes: [
      'Quadratisch, Kopf (Haaroberkante bis Kinn) 25–35 mm, Augenhöhe 1⅛–1⅜ Zoll vom unteren Rand.',
      'Hintergrund schlicht hell oder weiß, ohne Schatten und ohne Rahmen. Upload als JPEG, 10 kB bis 300 kB.',
    ],
    overrides: {
      eyeLineFromTop: 0.375,
      eyeLineRangeFromTop: [0.313, 0.437],
      digital: { formats: ['jpeg'], quality: 0.85, minWidthPx: 350, minHeightPx: 350, minBytes: 10_240, maxBytes: 307_200, aspectTolerancePercent: 0 },
      printSheets: ['4x6', 'a4'],
    },
  }),
  spec({
    id: 'cn-visa',
    region: 'CN',
    label: 'China – Visum (33 × 48 mm)',
    labelEn: 'China – visa (33 × 48 mm)',
    group: 'asia-pacific',
    widthMm: 33,
    heightMm: 48,
    headTargetMm: 31,
    headMinMm: 28,
    headMaxMm: 33,
    background: BG_WHITE,
    source: {
      label: 'Botschaft der VR China in der Schweiz – Fotoanforderungen Visum',
      url: 'https://ch.china-embassy.gov.cn/ger/ls_fw_s_1/sbqz/201612/t20161207_3420743.htm',
    },
    confidence: 'offiziell',
    notes: [
      'Kopfhöhe 28–33 mm, Kopfbreite 15–22 mm, Hintergrund weiß oder nahezu weiß, ohne Rahmen.',
      'Brille erlaubt außer dickem Rand, Tönung oder Spiegelung; Kopfbedeckung nur aus religiösen Gründen.',
    ],
    overrides: { faceWidth: { minMm: 15, maxMm: 22 } },
  }),
  spec({
    id: 'jp-passport',
    region: 'JP',
    label: 'Japan – Reisepass (35 × 45 mm)',
    labelEn: 'Japan – passport (35 × 45 mm)',
    group: 'asia-pacific',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: visafoto('jp-passport-photo', 'Japan – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'my-visa',
    region: 'MY',
    label: 'Malaysia – Visum / Pass (35 × 50 mm)',
    labelEn: 'Malaysia – visa / pass (35 × 50 mm)',
    group: 'asia-pacific',
    widthMm: 35,
    heightMm: 50,
    headTargetMm: 32.5,
    headMinMm: 30,
    headMaxMm: 35,
    topMarginMm: 5,
    background: { ...BG_WHITE, tones: ['weiss'] },
    source: { label: 'Imigresen Malaysia (ESD) – Photo Requirements', url: 'https://esd.imi.gov.my/portal/photo-requirements/' },
    confidence: 'offiziell',
    notes: [
      'Kinn bis Scheitel 30–35 mm, oben ca. 5 mm, unter dem Kinn 5–10 mm Rand.',
      'Weißer Hintergrund (für manche Pässe auch blau), Datei höchstens 25 kB.',
    ],
    overrides: { digital: { formats: ['jpeg'], quality: 0.8, maxBytes: 25_600 } },
  }),
  spec({
    id: 'sg-passport',
    region: 'SG',
    label: 'Singapur – Reisepass / Visum (35 × 45 mm)',
    labelEn: 'Singapore – passport / visa (35 × 45 mm)',
    group: 'asia-pacific',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    source: { label: 'ICA Singapore – Photo Guidelines', url: 'https://www.ica.gov.sg/photo-guidelines' },
    confidence: 'praxis',
    notes: [
      'Amtlich (ICA): Online-Upload empfohlen 400 × 514 px, JPG/PNG/HEIC, höchstens 8 MB, matt; keine Bildbearbeitung.',
      'Druckmaß und Kopfhöhe sind auf der ICA-Seite nicht im Text angegeben; hier gilt das ICAO-Raster.',
    ],
    overrides: { digital: { formats: ['jpeg', 'png'], quality: 0.92, widthPx: 400, heightPx: 514, maxBytes: 8_388_608 } },
  }),
  spec({
    id: 'th-visa',
    region: 'TH',
    label: 'Thailand – Visum (35 × 45 mm)',
    labelEn: 'Thailand – visa (35 × 45 mm)',
    group: 'asia-pacific',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: visafoto('th-visa-photo', 'Thailand – Visum'),
    confidence: 'praxis',
  }),
  spec({
    id: 'vn-visa',
    region: 'VN',
    label: 'Vietnam – Visum (40 × 60 mm)',
    labelEn: 'Vietnam – visa (40 × 60 mm)',
    group: 'asia-pacific',
    widthMm: 40,
    heightMm: 60,
    headTargetMm: 40,
    topMarginMm: 6,
    background: BG_LIGHT,
    source: visafoto('vn-visa-photo', 'Vietnam – Visum'),
    confidence: 'praxis',
    notes: ['Laut Angabe ohne Brille; beim E-Visum-Upload sehr kleine Dateien (ca. bis 45 kB).'],
    overrides: { glasses: 'verboten' },
  }),
  spec({
    id: 'bd-passport',
    region: 'BD',
    label: 'Bangladesch – Reisepass (40 × 50 mm)',
    labelEn: 'Bangladesh – passport (40 × 50 mm)',
    group: 'asia-pacific',
    widthMm: 40,
    heightMm: 50,
    headTargetMm: 34,
    topMarginMm: 5,
    source: visafoto('bd-passport-40x50-photo', 'Bangladesch – Reisepass'),
    confidence: 'praxis',
  }),
  spec({
    id: 'nz-passport',
    region: 'NZ',
    label: 'Neuseeland – Reisepass (digital 3:4)',
    labelEn: 'New Zealand – passport (digital 3:4)',
    group: 'asia-pacific',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34,
    headMinMm: 32,
    headMaxMm: 36,
    topMarginMm: 3,
    background: BG_LIGHT,
    source: {
      label: 'passports.govt.nz – Technical requirements',
      url: 'https://www.passports.govt.nz/passport-photos/check-your-photo-meets-the-technical-requirements',
    },
    confidence: 'praxis',
    notes: [
      'Amtlich: digital 900–4500 px breit und 1200–6000 px hoch, Seitenverhältnis 3:4, JPEG, 250 kB bis 5 MB, nicht älter als 6 Monate.',
      'Die Kopfhöhe ist auf der Seite nicht angegeben; hier gilt das ICAO-Raster.',
    ],
    overrides: {
      digital: {
        formats: ['jpeg'],
        quality: 0.92,
        minWidthPx: 900,
        minHeightPx: 1200,
        maxWidthPx: 4500,
        maxHeightPx: 6000,
        minBytes: 256_000,
        maxBytes: 5_242_880,
        aspectTolerancePercent: 4,
      },
    },
  }),
  spec({
    id: 'mx-passport',
    region: 'MX',
    label: 'Mexiko – Reisepass (35 × 45 mm)',
    labelEn: 'Mexico – passport (35 × 45 mm)',
    group: 'americas',
    widthMm: 35,
    heightMm: 45,
    headTargetMm: 34.5,
    topMarginMm: 4.5,
    source: visafoto('mx-passport-35x45-photo', 'Mexiko – Reisepass'),
    confidence: 'praxis',
  }),
]
