import type { Preset } from '../types'

const VERIFIED_AT = '2026-10-05'

export const UK_PRESET: Preset = {
  id: 'uk-passport',
  label: 'Vereinigtes Königreich – Reisepass (35 × 45 mm)',
  labelEn: 'United Kingdom – passport (35 × 45 mm)',
  group: 'eu',
  region: 'GB',
  widthMm: 35,
  heightMm: 45,
  dpi: 600,
  head: { minMm: 29, maxMm: 34, targetMm: 32 },
  topMarginMm: 5,
  freeSpaceTopRatio: 0.32,
  background: {
    tones: ['creme', 'hellgrau'],
    allowPureWhite: false,
    minLuminance: 0.55,
    minContrast: 0.12,
    uniformRequired: true,
  },
  glasses: 'ohne-tinte',
  headCovering: 'religioes',
  digital: {
    minWidthPx: 600,
    minHeightPx: 750,
    minBytes: 50_000,
    maxBytes: 10_485_760,
    formats: ['jpeg', 'png'],
    quality: 0.92,
    aspectTolerancePercent: 5,
  },
  printSheets: ['a4', '4x6'],
  printCopies: 2,
  maxAgeMonths: 1,
  notes: [
    'Bildhöhe Kinn–Scheitel 29–34 mm – engere Toleranz als im EU-Raster.',
    'Hintergrund cremefarben oder hellgrau; reines Weiß ist nicht zulässig.',
    'Digital: mindestens 600 × 750 px, 50 kB bis 10 MB, Farbe, unverändert.',
    'Das Foto muss im Antragsmonat aufgenommen worden sein.',
  ],
  source: {
    label: 'GOV.UK – Get a passport photo',
    url: 'https://www.gov.uk/photos-for-passports/photo-requirements',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const AUSTRALIA_PRESET: Preset = {
  id: 'au-passport',
  label: 'Australien – Reisepass (35–40 × 45–50 mm)',
  labelEn: 'Australia – passport (35–40 × 45–50 mm)',
  group: 'asia-pacific',
  region: 'AU',
  widthMm: 35,
  heightMm: 45,
  dpi: 600,
  head: { minMm: 32, maxMm: 36, targetMm: 34, minRatio: 0.7, maxRatio: 0.8 },
  topMarginMm: 3,
  freeSpaceTopRatio: 0.27,
  background: {
    tones: ['hellgrau', 'creme'],
    allowPureWhite: true,
    minLuminance: 0.6,
    minContrast: 0.12,
    uniformRequired: true,
  },
  glasses: 'ohne-tinte',
  headCovering: 'religioes',
  digital: {
    widthPx: 1200,
    heightPx: 1600,
    minBytes: 70_000,
    maxBytes: 3_670_016,
    formats: ['jpeg'],
    quality: 0.9,
    aspectTolerancePercent: 5,
  },
  printSheets: ['a4'],
  printCopies: 2,
  maxAgeMonths: 6,
  notes: [
    'Australien gibt eine Toleranz von 35–40 mm Breite und 45–50 mm Höhe vor; Export mit 35 × 45 mm.',
    'Digital-Antrag Citizenship: JPEG, bevorzugt 1200 × 1600 px, 70 kB bis 3,5 MB.',
  ],
  source: {
    label: 'passports.gov.au – Photo guidelines',
    url: 'https://www.passports.gov.au/getting-passport-how-it-works/photo-guidelines',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const INDIA_PRESET: Preset = {
  id: 'in-passport',
  label: 'Indien – Reisepass (35 × 45 mm)',
  labelEn: 'India – passport (35 × 45 mm)',
  group: 'asia-pacific',
  region: 'IN',
  widthMm: 35,
  heightMm: 45,
  dpi: 600,
  head: { minMm: 36, maxMm: 38, targetMm: 37, minRatio: 0.8, maxRatio: 0.85 },
  topMarginMm: 2.5,
  freeSpaceTopRatio: 0.2,
  background: {
    tones: ['weiss'],
    allowPureWhite: true,
    minLuminance: 0.8,
    minContrast: 0.16,
    uniformRequired: true,
  },
  glasses: 'ohne-reflexion',
  headCovering: 'religioes',
  digital: {
    widthPx: 630,
    heightPx: 810,
    maxBytes: 250_000,
    formats: ['jpeg'],
    quality: 0.9,
    aspectTolerancePercent: 0,
  },
  printSheets: ['a4'],
  printCopies: 4,
  maxAgeMonths: 6,
  notes: [
    'Aktueller Stand ist das ICAO-konforme Format 35 × 45 mm mit Kopfhöhe 36–38 mm (80–85 %).',
    'Reiner weißer Hintergrund erforderlich.',
    'Für den Inlandantrag gilt 630 × 810 px, JPEG, bis 250 kB; einzelne Botschaften verlangen 20–100 kB.',
    'Ältere indische amtliche Seiten nennen noch 51 × 51 mm – vor dem Einreichen Bestätigung einholen.',
  ],
  source: {
    label: 'passportindia.gov.in / VFS Checkliste',
    url: 'https://www.passportindia.gov.in/AppOnlineProject/online/procFormSubProcess',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'praxis',
}

export const CHINA_PRESET: Preset = {
  id: 'cn-passport',
  label: 'China – Reisepass (33 × 48 mm)',
  labelEn: 'China – passport (33 × 48 mm)',
  group: 'asia-pacific',
  region: 'CN',
  widthMm: 33,
  heightMm: 48,
  dpi: 600,
  head: { minMm: 28, maxMm: 33, targetMm: 31 },
  faceWidth: { minMm: 15, maxMm: 22 },
  topMarginMm: 4,
  freeSpaceTopRatio: 0.24,
  background: {
    tones: ['weiss'],
    allowPureWhite: true,
    minLuminance: 0.82,
    minContrast: 0.16,
    uniformRequired: true,
  },
  glasses: 'verboten',
  headCovering: 'verboten',
  digital: {
    formats: ['jpeg'],
    quality: 0.9,
    minWidthPx: 354,
    minHeightPx: 472,
    maxBytes: 120_000,
  },
  printSheets: ['a4'],
  printCopies: 2,
  maxAgeMonths: 6,
  notes: [
    'Kinn–Scheitel 28–33 mm, Kopfbreite 15–22 mm.',
    'Scheitel 3–5 mm vom oberen Rand, Kinn mindestens 7 mm vom unteren Rand.',
    'Reiner weißer Hintergrund, keine Kopfbedeckung, keine getönte Brille.',
    'Konsulate weichen ab: Los Angeles nennt 48 × 33 mm bei 21–24 mm Kopfbreite.',
  ],
  source: {
    label: 'Botschaft der VR China – Passbild',
    url: 'https://pg.china-embassy.gov.cn/chn/lsyw/lszj/hzlxz/hzlzyq/',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'offiziell',
}

export const JAPAN_PRESET: Preset = {
  id: 'jp-visa',
  label: 'Japan – Visum (45 × 35 mm)',
  labelEn: 'Japan – visa (45 × 35 mm)',
  group: 'asia-pacific',
  region: 'JP',
  widthMm: 35,
  heightMm: 45,
  dpi: 600,
  head: { minMm: 32, maxMm: 36, targetMm: 34 },
  topMarginMm: 3,
  freeSpaceTopRatio: 0.27,
  background: {
    tones: ['weiss', 'hellgrau'],
    allowPureWhite: true,
    minLuminance: 0.6,
    minContrast: 0.12,
    uniformRequired: true,
  },
  glasses: 'verboten',
  headCovering: 'verboten',
  digital: {
    formats: ['jpeg'],
    quality: 0.9,
    minWidthPx: 354,
    minHeightPx: 472,
    maxBytes: 300_000,
  },
  printSheets: ['a4'],
  printCopies: 1,
  maxAgeMonths: 6,
  notes: [
    'NICHT OFFIZIELL: Die japanischen Quellen widersprechen sich. Das Visumformular nennt 45 × 35 mm,',
    'Visumportale nennen teils 35 × 45 mm. Vor der Verwendung beim japanischen Konsulat bestätigen.',
  ],
  source: {
    label: 'MOFA – Visumantrag (unklare Angaben)',
    url: 'https://www.mofa.go.jp/',
  },
  verifiedAt: VERIFIED_AT,
  confidence: 'praxis',
}